import type { DeliveryStatus } from "@prisma/client";

/** Initial MVP scoring weights (sum = 100). Unknown factors are renormalized. */
export const SCORE_WEIGHTS = {
  PRICE: 40,
  ETA: 25,
  AVAILABILITY: 20,
  PROVIDER_PRIORITY: 10,
  SERVICE_QUALITY: 5,
} as const;

export const EXCLUSION_REASONS = {
  PROVIDER_NOT_ORCHESTRATION_ELIGIBLE: "PROVIDER_NOT_ORCHESTRATION_ELIGIBLE",
  ADAPTER_NOT_AVAILABLE: "ADAPTER_NOT_AVAILABLE",
  MISSING_REQUIRED_CAPABILITY: "MISSING_REQUIRED_CAPABILITY",
  ROUTE_NOT_SERVICEABLE: "ROUTE_NOT_SERVICEABLE",
  QUOTE_UNAVAILABLE: "QUOTE_UNAVAILABLE",
  NO_DRIVER_AVAILABILITY: "NO_DRIVER_AVAILABILITY",
  WEIGHT_EXCEEDS_PROVIDER_LIMIT: "WEIGHT_EXCEEDS_PROVIDER_LIMIT",
  WEIGHT_BELOW_PROVIDER_MINIMUM: "WEIGHT_BELOW_PROVIDER_MINIMUM",
  DIMENSIONS_EXCEED_PROVIDER_LIMIT: "DIMENSIONS_EXCEED_PROVIDER_LIMIT",
  PACKAGE_TYPE_NOT_SUPPORTED: "PACKAGE_TYPE_NOT_SUPPORTED",
  SCHEDULE_NOT_SUPPORTED: "SCHEDULE_NOT_SUPPORTED",
  REQUIREMENTS_NOT_SUPPORTED: "REQUIREMENTS_NOT_SUPPORTED",
} as const;

export type ExclusionReason =
  (typeof EXCLUSION_REASONS)[keyof typeof EXCLUSION_REASONS];

export const ORCHESTRATION_BLOCKED_STATUSES: DeliveryStatus[] = [
  "BOOKING",
  "BOOKED",
  "DRIVER_ASSIGNED",
  "PICKUP_OTP_PENDING",
  "PICKED_UP",
  "IN_TRANSIT",
  "DELIVERY_OTP_PENDING",
  "DELIVERED",
  "CANCELLED",
];

export const ORCHESTRATION_RETRYABLE_STATUSES: DeliveryStatus[] = [
  "CREATED",
  "FAILED",
];

/** Service types that support scheduled delivery windows. */
export const SCHEDULED_SERVICE_TYPES = new Set([
  "SCHEDULED",
  "EXPRESS",
  "SAME_DAY",
]);
