export const MAX_FEEDBACK_COMMENT_LENGTH = 1000;
export const MAX_TAGS_PER_CATEGORY = 6;

export const FEEDBACK_POSITIVE_TAGS = [
  "DRIVER_POLITE",
  "DRIVER_PROFESSIONAL",
  "FAST_DELIVERY",
  "EASY_BOOKING",
  "GOOD_COMMUNICATION",
  "PACKAGE_HANDLED_WELL",
] as const;

export const FEEDBACK_ISSUE_TAGS = [
  "DRIVER_LATE",
  "DRIVER_UNPROFESSIONAL",
  "DELIVERY_DELAYED",
  "COMMUNICATION_ISSUE",
  "PACKAGE_HANDLING_ISSUE",
  "TRACKING_ISSUE",
  "OTHER",
] as const;
